apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-shortener
spec:
  provider: vault
  secretObjects:
    - data:
      - key: MONGO_URI
        objectName: mongo-uri
      - key: AUTHN_URL
        objectName: authn-url
      - key: AUTHN_PASSWORD
        objectName: authn-password
      - key: authn-username
        objectName: authn-username
      secretName: shortener-secret
      type: Opaque
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "shortener"
    objects: |
      - objectName: "mongo-uri"
        secretPath: "secret/data/shortenersecret"
        secretKey: "MONGO_URI"
      - objectName: "authn-url"
        secretPath: "secret/data/shortenersecret"
        secretKey: "AUTHN_URL"
      - objectName: "authn-password"
        secretPath: "secret/data/shortenersecret"
        secretKey: "AUTHN_PASSWORD"
      - objectName: "authn-username"
        secretPath: "secret/data/shortenersecret"
        secretKey: "AUTHN_USERNAME"
