global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'shorter'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['shortner:2112']
  - job_name: 'mongo'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['mongodb-exporter:9216']
