apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "shortener.fullname" . }}-hpa
  labels:
  {{- include "shortener.labels" . | nindent 4 }}
spec:
  maxReplicas: 7
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shortener-deployment
  targetCPUUtilizationPercentage: 50