apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "shortener.fullname" . }}-ingress
  labels:
  {{- include "shortener.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: shortener.example.com
    http:
      paths:
      - backend:
          service:
            name: '{{ include "shortener.fullname" . }}-service'
            port:
              number: 80
        path: /
        pathType: Prefix