apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shortener.fullname" . }}-sa
  labels:
  {{- include "shortener.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.sa.serviceAccount.annotations | nindent 4 }}